# Generated by Django 5.2.9 on 2026-03-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_visitorlog_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('ai_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='running', max_length=50)),
                ('initial_plan', models.JSONField(blank=True, default=dict)),
                ('final_report', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('stage', models.CharField(default='execution', max_length=20)),
                ('depth', models.PositiveIntegerField(default=1)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tool', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_code', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('display_text', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recovery_attempts', models.PositiveIntegerField(default=0)),
                ('used_llm_fallback', models.BooleanField(default=False)),
                ('fallback_can_replace_execution', models.BooleanField(blank=True, null=True)),
                ('fallback_answer', models.TextField(blank=True, null=True)),
                ('fallback_raw_response', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='home.taskrun')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
    ]
