# Generated by Django 5.2.9 on 2026-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_taskrun_taskoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='source_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='source_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='source_sender_open_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='source_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
